# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# plugin for Git
[[plugins]]
repo = 'tpope/vim-fugitive'

# Session Manage
[[plugins]]
repo = 'skanehira/vsession'
hook_add = '''
let g:vsession_path = '~/.vim/sessions'
let g:vsession_save_last_on_leave = 0
let g:vsession_ui = 'quickpick'
'''

# airline
[[plugins]]
repo = 'vim-airline/vim-airline'

# autoclose
[[plugins]]
repo = 'Townk/vim-autoclose'

# vim-plugin doc generator
[[plugins]]
repo = 'LeafCage/vimhelpgenerator'

# translate
[[plugins]]
repo = 'skanehira/translate.vim'

# comment
[[plugins]]
repo = 'tomtom/tcomment_vim'

# indent visible
[[plugins]]
repo = 'Yggdroot/indentLine'

# complement
# [[plugins]]
# repo = 'davidhalter/jedi-vim'

# dart vim-plugin
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
hook_add = ' let g:dart_format_on_save = 1'


# nerdtree
[[plugins]]
repo = 'preservim/nerdtree'
hook_add = 'nnoremap <silent><C-e> :NERDTreeToggle<CR>'

#======== colorscheme =========
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'kuroitu/pyceberg'

[[plugins]]
repo = 'flrnd/plastic.vim'

[[plugins]]
repo = 'sainnhe/edge'

[[plugins]]
repo = 'cocopon/iceberg.vim'

#======== lang =======
# [[plugins]]
# repo = 'pangloss/vim-javascripto'

#======== lsp =======
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo =  'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

