# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# plugin for Git
[[plugins]]
repo = 'tpope/vim-fugitive'

# Session Manage
[[plugins]]
repo = 'skanehira/vsession'

# airline
[[plugins]]
repo = 'vim-airline/vim-airline'

# autoclose
[[plugins]]
repo = 'Townk/vim-autoclose'

# vim-plugin doc generator
[[plugins]]
repo = 'LeafCage/vimhelpgenerator'

# translate
[[plugins]]
repo = 'skanehira/translate.vim'

# comment
[[plugins]]
repo = 'tomtom/tcomment_vim'

# indent visible
[[plugins]]
repo = 'Yggdroot/indentLine'

# complement
[[plugins]]
repo = 'davidhalter/jedi-vim'

# dart vim-plugin
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

#======== colorscheme =========
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'kuroitu/pyceberg'

[[plugins]]
repo = 'flrnd/plastic.vim'

[[plugins]]
repo = 'sainnhe/edge'

[[plugins]]
repo = 'cocopon/iceberg.vim'
