# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# plugin for Git
[[plugins]]
repo = 'tpope/vim-fugitive'

# Session Manage
[[plugins]]
repo = 'skanehira/vsession'

# airline
[[plugins]]
repo = 'vim-airline/vim-airline'

# autoclose
[[plugins]]
repo = 'Townk/vim-autoclose'

# vim-plugin doc generator
[[plugins]]
repo = 'LeafCage/vimhelpgenerator'

#======== colorscheme =========
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'kuroitu/pyceberg'

[[plugins]]
repo = 'flrnd/plastic.vim'

[[plugins]]
repo = 'sainnhe/edge'

[[plugins]]
repo = 'cocopon/iceberg.vim'
